In [1]:
import tensorflow as tf
import keras
import numpy as np

Using TensorFlow backend.


In [21]:
stride = 8
anchors = np.asarray([[0,1,1,2],[0,3,5,1]])
#anchors_test = np.zeros((0,4))

shift_x = (np.arange(0, 12) + 0.5) * stride
shift_y = (np.arange(0, 6) + 0.5) * stride

shift_x, shift_y = np.meshgrid(shift_x, shift_y)

shifts = np.vstack((
    shift_x.ravel(), shift_y.ravel(),
    shift_x.ravel(), shift_y.ravel()
)).transpose()

print(shifts, shifts.shape)

A = anchors.shape[0] # number of anchors
K = shifts.shape[0] # number og shifts to make
all_anchors = (anchors.reshape((1, A, 4)) + shifts.reshape((1, K, 4)).transpose((1, 0, 2)))
print(all_anchors.ravel())
all_anchors = all_anchors.reshape((K*A, 4))
anchors_test = np.append(anchors_test, all_anchors, axis=0)

print(anchors_test, anchors_test.shape)

[[ 4.  4.  4.  4.]
 [12.  4. 12.  4.]
 [20.  4. 20.  4.]
 [28.  4. 28.  4.]
 [36.  4. 36.  4.]
 [44.  4. 44.  4.]
 [52.  4. 52.  4.]
 [60.  4. 60.  4.]
 [68.  4. 68.  4.]
 [76.  4. 76.  4.]
 [84.  4. 84.  4.]
 [92.  4. 92.  4.]
 [ 4. 12.  4. 12.]
 [12. 12. 12. 12.]
 [20. 12. 20. 12.]
 [28. 12. 28. 12.]
 [36. 12. 36. 12.]
 [44. 12. 44. 12.]
 [52. 12. 52. 12.]
 [60. 12. 60. 12.]
 [68. 12. 68. 12.]
 [76. 12. 76. 12.]
 [84. 12. 84. 12.]
 [92. 12. 92. 12.]
 [ 4. 20.  4. 20.]
 [12. 20. 12. 20.]
 [20. 20. 20. 20.]
 [28. 20. 28. 20.]
 [36. 20. 36. 20.]
 [44. 20. 44. 20.]
 [52. 20. 52. 20.]
 [60. 20. 60. 20.]
 [68. 20. 68. 20.]
 [76. 20. 76. 20.]
 [84. 20. 84. 20.]
 [92. 20. 92. 20.]
 [ 4. 28.  4. 28.]
 [12. 28. 12. 28.]
 [20. 28. 20. 28.]
 [28. 28. 28. 28.]
 [36. 28. 36. 28.]
 [44. 28. 44. 28.]
 [52. 28. 52. 28.]
 [60. 28. 60. 28.]
 [68. 28. 68. 28.]
 [76. 28. 76. 28.]
 [84. 28. 84. 28.]
 [92. 28. 92. 28.]
 [ 4. 36.  4. 36.]
 [12. 36. 12. 36.]
 [20. 36. 20. 36.]
 [28. 36. 28. 36.]
 [36. 36. 36

In [3]:
test_list = [[1,2],[0,1],[2,2],[4,4]]
test_list = tf.cast(test_list, dtype=tf.float32)

In [11]:
print(tf.norm(test_list, axis=1))

tf.Tensor([2.236068 1.       2.828427 5.656854], shape=(4,), dtype=float32)


In [34]:
regression = test_list

In [5]:
print(keras.backend.sum(test_list))

tf.Tensor(16.0, shape=(), dtype=float32)
