In [1]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

In [2]:
#define parameters
steps = 20
epochs = 25
batch_size = 8

## Train on On Pallet

In [7]:
!python "../../Vanilla/keras_retinanet/bin/train.py" --steps 396 --epochs 25 \
--weights "../../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 1 \
--compute-val-loss\
--name "Rotated_Comb_OP_train_set_14-04_05" \
csv "../OP_vanilla_train_set_14-04.csv" "../classes.csv" \
--val-annotations "../OP_vanilla_val_set_14-04.csv"

Using TensorFlow backend.
2020-05-05 08:35:28.699514: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-05 08:35:28.701762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-05-05 08:35:30.346814: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-05 08:35:30.389639: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-05 08:35:30.390953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-128.    ,  -32.    ,  128.    ,   32.    ],
       [-161.2672,  -40.3168,  161.2672,   40.3168],
       [-203.1872,  -50.7968,  203.1872,   50.7968]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-256.    ,  -64.    ,  256.    ,   64.    ],
       [-322.5344,  -80.6336,  322.5344,   80.6336],
       [-406.3744, -101.5936,  406.3744,  101.5936]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-512.    , -128.    ,  512.    ,  128.    ],
       [-645.0688, -161.2672,  645.0688,  161.2672],
       [-812.7488, -203.1872,  812.7488,  203.1872]], dtype=float32)> anchors
regression Tensor("split/stack:0", shape=(None, None, 4), dtype=float32)
other Tensor("split/stack_1:0", shape=(None, None, 2), dtype=float32)
boxes Tensor("clipped_boxes/stack:0", shape=(None, None, 4), dtype=float32)
Model: "retinanet"


Epoch 1/25
../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_492.png with id 256 (shape (720, 1280, 3)) contains the following invalid boxes [[868.0336   188.71841  824.2425   169.69699  903.3951   -12.527908
  947.1862     6.493515]] or angles [[-0.68254528 -0.73084331]].
  annotations['angles'][invalid_indices, :]
2020-05-05 08:35:55.231465: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-05 08:35:56.711874: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
 30/396 [=>............................] - ETA: 4:59 - loss: 4.4723 - bbox_regression_loss: 3.3153 - classification_loss: 1.1570../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_o

244/396 [=================>............] - ETA: 47s - loss: 1.6297 - bbox_regression_loss: 1.4244 - classification_loss: 0.2053../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_492.png with id 256 (shape (720, 1280, 3)) contains the following invalid boxes [[868.0336   188.71841  824.2425   169.69699  903.3951   -12.527908
  947.1862     6.493515]] or angles [[-0.68254528 -0.73084331]].
  annotations['angles'][invalid_indices, :]
262/396 [==================>...........] - ETA: 42s - loss: 1.6107 - bbox_regression_loss: 1.4076 - classification_loss: 0.2031../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_498.png with id 226 (shape (720, 1280, 3)) contains the following invalid boxes [[869.666     188.94604   824.5969    169.95627   901.71765   -13.07717

Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:15 Time:  0:00:15
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00009: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_09.h5
Epoch 10/25
396/396 [==============================] - 136s 343ms/step - loss: 0.3197 - bbox_regression_loss: 0.2911 - classification_loss: 0.0287 - val_loss: 0.0903 - val_bbox_regression_loss: 0.3837 - val_classification_loss: 0.0442
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:16 Time:  0:00:16
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00010: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_10.h5
Epoch 11/25
396/396 [==============================] - 138s 348ms/step - loss: 0.2913 - bbox_regression_loss: 0.2650 - classifica

## Continue Training from Snapshot

In [ ]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 99 --epochs 50 \
--snapshot "./02 On Pallet Dataset/01 Snapshots/resnet50_csv_25.h5" \
--initial-epoch 25 \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 4 \
--compute-val-loss\
--random-transform\
--name "Rotated_Comb_OP_train_set_14-04_rndTrans_BS4_25-50" \
csv "../OP_train_set_14-04.csv" "../classes.csv" \
--val-annotations "../OP_val_set_14-04.csv"

## Train on Simple Dataset

In [1]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 162 --epochs 25 \
--weights "../../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--snapshot-path "./01 Simple Dataset/01 Snapshots" \
--batch-size 1 \
--compute-val-loss\
--name "Rotated_Comb_train_set_18-03_05" \
csv "../train_set_18-03.csv" "../classes.csv" \
--val-annotations "../val_set_18-03.csv"

Using TensorFlow backend.
2020-05-05 01:35:29.749810: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-05 01:35:29.806443: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-05-05 01:35:32.405989: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-05 01:35:32.481301: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-05 01:35:32.482430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-128.    ,  -32.    ,  128.    ,   32.    ],
       [-161.2672,  -40.3168,  161.2672,   40.3168],
       [-203.1872,  -50.7968,  203.1872,   50.7968]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-256.    ,  -64.    ,  256.    ,   64.    ],
       [-322.5344,  -80.6336,  322.5344,   80.6336],
       [-406.3744, -101.5936,  406.3744,  101.5936]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-512.    , -128.    ,  512.    ,  128.    ],
       [-645.0688, -161.2672,  645.0688,  161.2672],
       [-812.7488, -203.1872,  812.7488,  203.1872]], dtype=float32)> anchors
regression Tensor("split/stack:0", shape=(None, None, 4), dtype=float32)
other Tensor("split/stack_1:0", shape=(None, None, 2), dtype=float32)
boxes Tensor("clipped_boxes/stack:0", shape=(None, None, 4), dtype=float32)
Model: "retinanet"


Epoch 1/25
2020-05-05 01:35:57.864225: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-05 01:36:00.434490: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
162/162 [==============================] - 63s 390ms/step - loss: 3.1729 - bbox_regression_loss: 2.3892 - classification_loss: 0.7838 - val_loss: 2.7372 - val_bbox_regression_loss: 1.6873 - val_classification_loss: 0.2012
Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:06 Time:  0:00:06
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00001: saving model to ./01 Simple Dataset/01 Snapshots/resnet50_csv_01.h5
Epoch 2/25
162/162 [==============================] - 48s 295ms/step - loss: 1.5231 - bbox_regression_loss: 1.3667 - classification_loss: 0.1563 - val_loss: 2.0113 - v