In [1]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

In [2]:
#define parameters
steps = 20
epochs = 25
batch_size = 8

## Train on On Pallet

In [11]:
!python "../../keras-retinanet-vanilla/keras_retinanet/bin/train.py" --steps 396 --epochs 25 \
--weights "../../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 1 \
--compute-val-loss\
--name "Vanilla_OP_train_set_14-04_05" \
csv "../OP_vanilla_train_set_14-04.csv" "../classes.csv" \
--val-annotations "../OP_vanilla_val_set_14-04.csv"

Using TensorFlow backend.
2020-05-07 13:10:34.619871: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-07 13:10:34.621348: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-05-07 13:10:35.500002: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-07 13:10:35.527200: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-07 13:10:35.528212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[ -90.50967 ,  -45.254833,   90.50967 ,   45.254833],
       [-114.03504 ,  -57.01752 ,  114.03504 ,   57.01752 ],
       [-143.67514 ,  -71.83757 ,  143.67514 ,   71.83757 ],
       [ -64.      ,  -64.      ,   64.      ,   64.      ],
       [ -80.63495 ,  -80.63495 ,   80.63495 ,   80.63495 ],
       [-101.593666, -101.593666,  101.593666,  101.593666],
       [ -45.254833,  -90.50967 ,   45.254833,   90.50967 ],
       [ -57.01752 , -114.03504 ,   57.01752 ,  114.03504 ],
       [ -71.83757 , -143.67514 ,   71.83757 ,  143.67514 ]],
      dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-181.01933,  -90.50967,  181.01933,   90.50967],
       [-228.07008, -114.03504,  228.07008,  114.03504],
       [-287.35028, -143.67514,  287.35028,  143.67514],
       [-128.     , -128.     ,  128.     ,  128.     ],
       [-161.2699 , -161.2699 ,  161.2699 ,  161.269

Epoch 1/25
2020-05-07 13:10:55.832854: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-07 13:10:56.809481: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
 76/396 [====>.........................] - ETA: 2:31 - loss: 2.4349 - regression_loss: 1.2968 - classification_loss: 1.1382../../keras-retinanet-vanilla/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:181: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_499.png with id 167 (shape (720, 1280, 3)) contains the following invalid boxes: [[825.  -1. 949. 187.]].
  annotations['bboxes'][invalid_indices, :]
171/396 [===========>..................] - ETA: 1:25 - loss: 1.9671 - regression_loss: 0.9669 - classification_loss: 1.0002../../keras-retinanet-vanilla/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:181: UserWarning: Image ../../../03 Da

1157 instances of class Brick with average precision: 0.9736
mAP: 0.9736

Epoch 00004: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_04.h5
Epoch 5/25
396/396 [==============================] - 132s 333ms/step - loss: 0.3897 - regression_loss: 0.3609 - classification_loss: 0.0288 - val_loss: 0.1340 - val_regression_loss: 0.3800 - val_classification_loss: 0.0356
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.9717
mAP: 0.9717

Epoch 00005: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_05.h5
Epoch 6/25
396/396 [==============================] - 132s 332ms/step - loss: 0.3580 - regression_loss: 0.3362 - classification_loss: 0.0219 - val_loss: 0.4183 - val_regression_loss: 0.3655 - val_classification_loss: 0.0397
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00

Epoch 20/25
396/396 [==============================] - 132s 334ms/step - loss: 0.2078 - regression_loss: 0.2045 - classification_loss: 0.0033 - val_loss: 1.1545 - val_regression_loss: 0.2664 - val_classification_loss: 0.0352
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.9899
mAP: 0.9899

Epoch 00020: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_20.h5
Epoch 21/25
396/396 [==============================] - 132s 334ms/step - loss: 0.1995 - regression_loss: 0.1969 - classification_loss: 0.0027 - val_loss: 0.1720 - val_regression_loss: 0.2660 - val_classification_loss: 0.0209
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.9900
mAP: 0.9900

## Continue Training from Snapshot

In [ ]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 99 --epochs 50 \
--snapshot "./02 On Pallet Dataset/01 Snapshots/resnet50_csv_25.h5" \
--initial-epoch 25 \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 4 \
--compute-val-loss\
--random-transform\
--name "Rotated_Comb_OP_train_set_14-04_rndTrans_BS4_25-50" \
csv "../OP_train_set_14-04.csv" "../classes.csv" \
--val-annotations "../OP_val_set_14-04.csv"

## Train on Simple Dataset

In [6]:
!python "../../keras-retinanet-vanilla/keras_retinanet/bin/train.py" --steps 162 --epochs 25 \
--weights "../../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--snapshot-path "./01 Simple Dataset/01 Snapshots" \
--batch-size 1 \
--compute-val-loss\
--name "Vanilla_train_set_18-03_05" \
csv "../vanilla_train_set_18-03.csv" "../classes.csv" \
--val-annotations "../vanilla_val_set_18-03.csv"

Using TensorFlow backend.
2020-05-08 04:35:47.255031: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-08 04:35:47.256657: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-05-08 04:35:48.106209: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-08 04:35:48.134565: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-08 04:35:48.135637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[ -90.50967 ,  -45.254833,   90.50967 ,   45.254833],
       [-114.03504 ,  -57.01752 ,  114.03504 ,   57.01752 ],
       [-143.67514 ,  -71.83757 ,  143.67514 ,   71.83757 ],
       [ -64.      ,  -64.      ,   64.      ,   64.      ],
       [ -80.63495 ,  -80.63495 ,   80.63495 ,   80.63495 ],
       [-101.593666, -101.593666,  101.593666,  101.593666],
       [ -45.254833,  -90.50967 ,   45.254833,   90.50967 ],
       [ -57.01752 , -114.03504 ,   57.01752 ,  114.03504 ],
       [ -71.83757 , -143.67514 ,   71.83757 ,  143.67514 ]],
      dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-181.01933,  -90.50967,  181.01933,   90.50967],
       [-228.07008, -114.03504,  228.07008,  114.03504],
       [-287.35028, -143.67514,  287.35028,  143.67514],
       [-128.     , -128.     ,  128.     ,  128.     ],
       [-161.2699 , -161.2699 ,  161.2699 ,  161.269

Epoch 1/25
2020-05-08 04:36:08.613501: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-08 04:36:09.604117: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
162/162 [==============================] - 62s 380ms/step - loss: 1.6645 - regression_loss: 0.7079 - classification_loss: 0.9566 - val_loss: 1.3996 - val_regression_loss: 0.4868 - val_classification_loss: 0.4058
Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:06 Time:  0:00:06
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.7627
mAP: 0.7627

Epoch 00001: saving model to ./01 Simple Dataset/01 Snapshots/resnet50_csv_01.h5
Epoch 2/25
162/162 [==============================] - 48s 297ms/step - loss: 0.6669 - regression_loss: 0.4786 - classification_loss: 0.1884 - val_loss: 0.5196 - val_regression_l

640 instances of class Brick with average precision: 0.9947
mAP: 0.9947

Epoch 00015: saving model to ./01 Simple Dataset/01 Snapshots/resnet50_csv_15.h5
Epoch 16/25
162/162 [==============================] - 49s 304ms/step - loss: 0.2657 - regression_loss: 0.2602 - classification_loss: 0.0054 - val_loss: 0.2261 - val_regression_loss: 0.2748 - val_classification_loss: 0.0069
Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:04 Time:  0:00:04
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.9924
mAP: 0.9924

Epoch 00016: saving model to ./01 Simple Dataset/01 Snapshots/resnet50_csv_16.h5
Epoch 17/25
162/162 [==============================] - 49s 304ms/step - loss: 0.2569 - regression_loss: 0.2522 - classification_loss: 0.0047 - val_loss: 0.2194 - val_regression_loss: 0.2770 - val_classification_loss: 0.0065
Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:04 Time:  0:00:04
Pars