In [ ]:
#%matplotlib inline

import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

In [ ]:
#define parameters
steps = 20
epochs = 25
batch_size = 8

In [2]:
!python "../RetinaNet with Angle/keras_retinanet/bin/train.py" --steps 162 --epochs 25 \
--weights "../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--freeze-backbone \
--batch-size 1 \
--compute-val-loss\
csv train_set_18-03.csv classes.csv \
--val-annotations val_set_18-03.csv 

Using TensorFlow backend.
2020-03-31 06:10:12.422248: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-31 06:10:12.424238: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-03-31 06:10:13.463241: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-31 06:10:13.486762: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-31 06:10:13.487937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[ -90.50967 ,  -45.254833,   90.50967 ,   45.254833],
       [-114.03504 ,  -57.01752 ,  114.03504 ,   57.01752 ],
       [-143.67514 ,  -71.83757 ,  143.67514 ,   71.83757 ],
       [ -64.      ,  -64.      ,   64.      ,   64.      ],
       [ -80.63495 ,  -80.63495 ,   80.63495 ,   80.63495 ],
       [-101.593666, -101.593666,  101.593666,  101.593666],
       [ -45.254833,  -90.50967 ,   45.254833,   90.50967 ],
       [ -57.01752 , -114.03504 ,   57.01752 ,  114.03504 ],
       [ -71.83757 , -143.67514 ,   71.83757 ,  143.67514 ]],
      dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-181.01933,  -90.50967,  181.01933,   90.50967],
       [-228.07008, -114.03504,  228.07008,  114.03504],
       [-287.35028, -143.67514,  287.35028,  143.67514],
       [-128.     , -128.     ,  128.     ,  128.     ],
       [-161.2699 , -161.2699 ,  161.2699 ,  161.269

Epoch 1/25
2020-03-31 06:10:29.457720: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-31 06:10:30.556267: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
162/162 [==============================] - 44s 274ms/step - loss: 2.7380 - regression_loss: 0.9624 - classification_loss: 0.9123 - angle_regression_loss: 0.8634 - val_loss: 2.7469 - val_regression_loss: 0.7184 - val_classification_loss: 0.4056 - val_angle_regression_loss: 0.5217
Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:08 Time:  0:00:08
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00001: saving model to ./snapshots/resnet50_csv_01.h5
Epoch 2/25
162/162 [==============================] - 35s 218ms/step - loss: 1.5137 - regression_loss: 0.7197 - classification_los

Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:04 Time:  0:00:04
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00014: saving model to ./snapshots/resnet50_csv_14.h5
Epoch 15/25
162/162 [==============================] - 36s 220ms/step - loss: 0.5519 - regression_loss: 0.4098 - classification_loss: 0.0276 - angle_regression_loss: 0.1145 - val_loss: 0.6884 - val_regression_loss: 0.4012 - val_classification_loss: 0.0273 - val_angle_regression_loss: 0.0859
Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:04 Time:  0:00:04
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00015: saving model to ./snapshots/resnet50_csv_15.h5
Epoch 16/25
162/162 [==============================] - 36s 219ms/step - loss: 0.5233 - regression_loss: 0.4007 - classific

## Retraining of Test networks

In [3]:
!python "../RetinaNet with Angle/keras_retinanet/bin/train.py" --steps 162 --epochs 40 \
--snapshot snapshots/resnet50_csv_25.h5 \
--initial-epoch 25 \
--compute-val-loss\
csv train_set_18-03.csv classes.csv \
--val-annotations val_set_18-03.csv 

Using TensorFlow backend.
2020-03-31 06:31:26.981312: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-31 06:31:26.983063: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Loading model, this may take a second...
2020-03-31 06:31:28.091411: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-31 06:31:28.119932: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-31 06:31:28.121054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00GiB

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[ -90.50967 ,  -45.254833,   90.50967 ,   45.254833],
       [-114.03504 ,  -57.01752 ,  114.03504 ,   57.01752 ],
       [-143.67514 ,  -71.83757 ,  143.67514 ,   71.83757 ],
       [ -64.      ,  -64.      ,   64.      ,   64.      ],
       [ -80.63495 ,  -80.63495 ,   80.63495 ,   80.63495 ],
       [-101.593666, -101.593666,  101.593666,  101.593666],
       [ -45.254833,  -90.50967 ,   45.254833,   90.50967 ],
       [ -57.01752 , -114.03504 ,   57.01752 ,  114.03504 ],
       [ -71.83757 , -143.67514 ,   71.83757 ,  143.67514 ]],
      dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-181.01933,  -90.50967,  181.01933,   90.50967],
       [-228.07008, -114.03504,  228.07008,  114.03504],
       [-287.35028, -143.67514,  287.35028,  143.67514],
       [-128.     , -128.     ,  128.     ,  128.     ],
       [-161.2699 , -161.2699 ,  161.2699 ,  161.269

Epoch 26/40
2020-03-31 06:31:42.623984: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-31 06:31:43.711523: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
162/162 [==============================] - 45s 277ms/step - loss: 0.4086 - regression_loss: 0.3487 - classification_loss: 0.0156 - angle_regression_loss: 0.0443 - val_loss: 0.4962 - val_regression_loss: 0.3581 - val_classification_loss: 0.0167 - val_angle_regression_loss: 0.0452
Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:07 Time:  0:00:07
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00026: saving model to ./snapshots/resnet50_csv_26.h5
Epoch 27/40
162/162 [==============================] - 36s 221ms/step - loss: 0.4017 - regression_loss: 0.3430 - classification_l

Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:04 Time:  0:00:04
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00039: saving model to ./snapshots/resnet50_csv_39.h5
Epoch 40/40
162/162 [==============================] - 36s 222ms/step - loss: 0.3262 - regression_loss: 0.2920 - classification_loss: 0.0094 - angle_regression_loss: 0.0247 - val_loss: 0.4217 - val_regression_loss: 0.3308 - val_classification_loss: 0.0117 - val_angle_regression_loss: 0.0408
Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:04 Time:  0:00:04
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00040: saving model to ./snapshots/resnet50_csv_40.h5
{'val_loss': [0.4961584210395813, 0.44821447134017944, 0.45253831148147583, 0.4873293340206146, 0.4649609327316284, 0.4436

In [ ]:
!python ../keras-retinanet/keras_retinanet/bin/train.py --steps 162 --epochs 35 --snapshot-path ../keras-retinanet/snapshots \
--weights ../keras-retinanet/snapshots/resnet50_coco_best_v2.1.0.h5 \
--batch-size 1 \
--compute-val-loss\
csv train_set_03-03.csv classes.csv \
--val-annotations val_set_03-03.csv 

In [ ]:
!python ../keras-retinanet/keras_retinanet/bin/train.py --steps 162 --epochs 50 --snapshot-path ../keras-retinanet/snapshots \
--snapshot ../keras-retinanet/snapshots/resnet50_csv_25.h5 \
--initial-epoch 25 \
--no-resize --batch-size 1 \
--compute-val-loss\
csv train_set_03-03.csv classes.csv \
--val-annotations val_set_03-03.csv 

In [ ]:
loss_data = genfromtxt('val_train_set_03-03_losses.csv', delimiter=',')
loss_data = loss_data.T
print(loss_data)

In [ ]:
plt.figure(figsize=(4, 3), dpi=200)
plt.plot(range(1, 1 + len(loss_data[0])), loss_data[0])
plt.plot(range(1, 1 + len(loss_data[1])), loss_data[1])
plt.legend(['Train Loss','Validation Loss'])
plt.title('Steps: 162, BS: 1, BB: renet50-coco, resized')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.savefig('./val_train_set_03-03_losses_resize.png',bbox_inches='tight')