In [ ]:
#%matplotlib inline

import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

In [ ]:
#define parameters
steps = 20
epochs = 25
batch_size = 8

In [1]:
!python "../RetinaNet with Angle/keras_retinanet/bin/train.py" --steps 162 --epochs 25 \
--weights "../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--batch-size 1 \
csv train_set_18-03.csv classes.csv 

Using TensorFlow backend.
2020-03-24 08:34:38.860055: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-24 08:34:38.861595: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-03-24 08:34:39.730203: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-24 08:34:39.760154: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-24 08:34:39.761322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[ -90.50967 ,  -45.254833,   90.50967 ,   45.254833],
       [-114.03504 ,  -57.01752 ,  114.03504 ,   57.01752 ],
       [-143.67514 ,  -71.83757 ,  143.67514 ,   71.83757 ],
       [ -64.      ,  -64.      ,   64.      ,   64.      ],
       [ -80.63495 ,  -80.63495 ,   80.63495 ,   80.63495 ],
       [-101.593666, -101.593666,  101.593666,  101.593666],
       [ -45.254833,  -90.50967 ,   45.254833,   90.50967 ],
       [ -57.01752 , -114.03504 ,   57.01752 ,  114.03504 ],
       [ -71.83757 , -143.67514 ,   71.83757 ,  143.67514 ]],
      dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-181.01933,  -90.50967,  181.01933,   90.50967],
       [-228.07008, -114.03504,  228.07008,  114.03504],
       [-287.35028, -143.67514,  287.35028,  143.67514],
       [-128.     , -128.     ,  128.     ,  128.     ],
       [-161.2699 , -161.2699 ,  161.2699 ,  161.269

res4e (Add)                     (None, None, None, 1 0           bn4e_branch2c[0][0]              
                                                                 res4d_relu[0][0]                 
__________________________________________________________________________________________________
res4e_relu (Activation)         (None, None, None, 1 0           res4e[0][0]                      
__________________________________________________________________________________________________
res4f_branch2a (Conv2D)         (None, None, None, 2 262144      res4e_relu[0][0]                 
__________________________________________________________________________________________________
bn4f_branch2a (BatchNormalizati (None, None, None, 2 1024        res4f_branch2a[0][0]             
__________________________________________________________________________________________________
res4f_branch2a_relu (Activation (None, None, None, 2 0           bn4f_branch2a[0][0]              
__________

Epoch 1/25
2020-03-24 08:35:02.260521: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-24 08:35:03.272069: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
162/162 [==============================] - 66s 406ms/step - loss: 2.4779 - regression_loss: 0.6839 - classification_loss: 0.8990 - angle_regression_loss: 0.8950

Epoch 00001: saving model to ./snapshots/resnet50_csv_01.h5
Epoch 2/25
162/162 [==============================] - 51s 316ms/step - loss: 1.2627 - regression_loss: 0.4822 - classification_loss: 0.3155 - angle_regression_loss: 0.4650

Epoch 00002: saving model to ./snapshots/resnet50_csv_02.h5
Epoch 3/25
162/162 [==============================] - 52s 321ms/step - loss: 0.9442 - regression_loss: 0.4348 - classification_loss: 0.1118 - angle_regression_loss: 0.3976

Epoch 00003: saving model to ./snapshots/resnet50_csv_03.h5
Epoch 4/25
162/

## Retraining of Test networks

In [1]:
!python "../RetinaNet with Angle/keras_retinanet/bin/train.py" --steps 162 --epochs 50 \
--snapshot snapshots/Full_Unit_Circle_SmoothL1_resnet50_csv_25.h5 \
--initial-epoch 25 \
csv train_set_18-03.csv classes.csv 

Using TensorFlow backend.
2020-03-31 05:29:41.235333: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-31 05:29:41.295639: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Loading model, this may take a second...
2020-03-31 05:29:44.053904: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-31 05:29:44.100921: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-31 05:29:44.102125: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00GiB

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[ -90.50967 ,  -45.254833,   90.50967 ,   45.254833],
       [-114.03504 ,  -57.01752 ,  114.03504 ,   57.01752 ],
       [-143.67514 ,  -71.83757 ,  143.67514 ,   71.83757 ],
       [ -64.      ,  -64.      ,   64.      ,   64.      ],
       [ -80.63495 ,  -80.63495 ,   80.63495 ,   80.63495 ],
       [-101.593666, -101.593666,  101.593666,  101.593666],
       [ -45.254833,  -90.50967 ,   45.254833,   90.50967 ],
       [ -57.01752 , -114.03504 ,   57.01752 ,  114.03504 ],
       [ -71.83757 , -143.67514 ,   71.83757 ,  143.67514 ]],
      dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-181.01933,  -90.50967,  181.01933,   90.50967],
       [-228.07008, -114.03504,  228.07008,  114.03504],
       [-287.35028, -143.67514,  287.35028,  143.67514],
       [-128.     , -128.     ,  128.     ,  128.     ],
       [-161.2699 , -161.2699 ,  161.2699 ,  161.269

bn3d_branch2a (BatchNormalizati (None, None, None, 1 512         res3d_branch2a[0][0]             
__________________________________________________________________________________________________
res3d_branch2a_relu (Activation (None, None, None, 1 0           bn3d_branch2a[0][0]              
__________________________________________________________________________________________________
padding3d_branch2b (ZeroPadding (None, None, None, 1 0           res3d_branch2a_relu[0][0]        
__________________________________________________________________________________________________
res3d_branch2b (Conv2D)         (None, None, None, 1 147456      padding3d_branch2b[0][0]         
__________________________________________________________________________________________________
bn3d_branch2b (BatchNormalizati (None, None, None, 1 512         res3d_branch2b[0][0]             
__________________________________________________________________________________________________
res3d_bran

2020-03-31 05:30:24.990115: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-31 05:30:27.356683: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
162/162 [==============================] - 70s 431ms/step - loss: 0.2534 - regression_loss: 0.2264 - classification_loss: 0.0037 - angle_regression_loss: 0.0233

Epoch 00026: saving model to ./snapshots/resnet50_csv_26.h5
Epoch 27/50
162/162 [==============================] - 51s 314ms/step - loss: 0.2527 - regression_loss: 0.2243 - classification_loss: 0.0034 - angle_regression_loss: 0.0250

Epoch 00027: saving model to ./snapshots/resnet50_csv_27.h5
Epoch 28/50
162/162 [==============================] - 51s 315ms/step - loss: 0.2413 - regression_loss: 0.2183 - classification_loss: 0.0033 - angle_regression_loss: 0.0198

Epoch 00028: saving model to ./snapshots/resnet50_csv_28.h5
Epoch 29/50
162/162 [===

In [ ]:
!python ../keras-retinanet/keras_retinanet/bin/train.py --steps 162 --epochs 35 --snapshot-path ../keras-retinanet/snapshots \
--weights ../keras-retinanet/snapshots/resnet50_coco_best_v2.1.0.h5 \
--batch-size 1 \
--compute-val-loss\
csv train_set_03-03.csv classes.csv \
--val-annotations val_set_03-03.csv 

In [ ]:
!python ../keras-retinanet/keras_retinanet/bin/train.py --steps 162 --epochs 50 --snapshot-path ../keras-retinanet/snapshots \
--snapshot ../keras-retinanet/snapshots/resnet50_csv_25.h5 \
--initial-epoch 25 \
--no-resize --batch-size 1 \
--compute-val-loss\
csv train_set_03-03.csv classes.csv \
--val-annotations val_set_03-03.csv 

In [ ]:
loss_data = genfromtxt('val_train_set_03-03_losses.csv', delimiter=',')
loss_data = loss_data.T
print(loss_data)

In [ ]:
plt.figure(figsize=(4, 3), dpi=200)
plt.plot(range(1, 1 + len(loss_data[0])), loss_data[0])
plt.plot(range(1, 1 + len(loss_data[1])), loss_data[1])
plt.legend(['Train Loss','Validation Loss'])
plt.title('Steps: 162, BS: 1, BB: renet50-coco, resized')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.savefig('./val_train_set_03-03_losses_resize.png',bbox_inches='tight')