In [ ]:
#%matplotlib inline

import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

In [ ]:
#define parameters
steps = 20
epochs = 25
batch_size = 8

In [1]:
!python "../RetinaNet with Angle/keras_retinanet/bin/train.py" --steps 162 --epochs 1 \
--weights "../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--batch-size 1 \
--compute-val-loss\
csv train_set_18-03.csv classes.csv \
--val-annotations val_set_18-03.csv 

Creating model, this may take a second...
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-22.627417, -11.313708,  22.627417,  11.313708],
       [-28.50876 , -14.25438 ,  28.50876 ,  14.25438 ],
       [-35.918785, -17.959393,  35.918785,  17.959393],
       [-16.      , -16.      ,  16.      ,  16.      ],
       [-20.158737, -20.158737,  20.158737,  20.158737],
       [-25.398417, -25.398417,  25.398417,  25.398417],
       [-11.313708, -22.627417,  11.313708,  22.627417],
       [-14.25438 , -28.50876 ,  14.25438 ,  28.50876 ],
       [-17.959393, -35.918785,  17.959393,  35.918785]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-45.254833, -22.627417,  45.254833,  22.627417],
       [-57.01752 , -28.50876 ,  57.01752 ,  28.50876 ],
       [-71.83757 , -35.918785,  71.83757 ,  35.918785],
       [-32.      , -32.      ,  32.      ,  32.      ],
       [-40.317474, -40.317474,  40.317474,  40.3174

2020-03-27 13:40:53.853786: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-03-27 13:40:53.854175: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-03-27 13:40:56.508570: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-03-27 13:40:56.508968: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-27 13:40:56.513577: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-GPUASTH
2020-03-27 13:40:56.514018: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-GPUASTH
2020-03-27 13:40:56.514493: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instruc

       [-287.35028, -143.67514,  287.35028,  143.67514],
       [-128.     , -128.     ,  128.     ,  128.     ],
       [-161.2699 , -161.2699 ,  161.2699 ,  161.2699 ],
       [-203.18733, -203.18733,  203.18733,  203.18733],
       [ -90.50967, -181.01933,   90.50967,  181.01933],
       [-114.03504, -228.07008,  114.03504,  228.07008],
       [-143.67514, -287.35028,  143.67514,  287.35028]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-362.03867, -181.01933,  362.03867,  181.01933],
       [-456.14017, -228.07008,  456.14017,  228.07008],
       [-574.70056, -287.35028,  574.70056,  287.35028],
       [-256.     , -256.     ,  256.     ,  256.     ],
       [-322.5398 , -322.5398 ,  322.5398 ,  322.5398 ],
       [-406.37466, -406.37466,  406.37466,  406.37466],
       [-181.01933, -362.03867,  181.01933,  362.03867],
       [-228.07008, -456.14017,  228.07008,  456.14017],
       [-287.35028, -574.70056,  287.35028,  574.7

In [ ]:
!python ../keras-retinanet/keras_retinanet/bin/train.py --steps 162 --epochs 35 --snapshot-path ../keras-retinanet/snapshots \
--weights ../keras-retinanet/snapshots/resnet50_coco_best_v2.1.0.h5 \
--batch-size 1 \
--compute-val-loss\
csv train_set_03-03.csv classes.csv \
--val-annotations val_set_03-03.csv 

In [ ]:
!python ../keras-retinanet/keras_retinanet/bin/train.py --steps 162 --epochs 50 --snapshot-path ../keras-retinanet/snapshots \
--snapshot ../keras-retinanet/snapshots/resnet50_csv_25.h5 \
--initial-epoch 25 \
--no-resize --batch-size 1 \
--compute-val-loss\
csv train_set_03-03.csv classes.csv \
--val-annotations val_set_03-03.csv 

In [ ]:
loss_data = genfromtxt('val_train_set_03-03_losses.csv', delimiter=',')
loss_data = loss_data.T
print(loss_data)

In [ ]:
plt.figure(figsize=(4, 3), dpi=200)
plt.plot(range(1, 1 + len(loss_data[0])), loss_data[0])
plt.plot(range(1, 1 + len(loss_data[1])), loss_data[1])
plt.legend(['Train Loss','Validation Loss'])
plt.title('Steps: 162, BS: 1, BB: renet50-coco, resized')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.savefig('./val_train_set_03-03_losses_resize.png',bbox_inches='tight')