In [9]:
import cv2


box1 = ((200,100),(100,30),10)
box2 = ((200,100),(110,30),12)
box3 = ((220,105),(90,30),5)
box_list = [box1,box2,box3]
scores = [0.6,0.8,0.4]



indices=cv2.dnn.NMSBoxesRotated(box_list, scores, 0.3, 0.8)
print(indices.flatten())
print(box_list[int(indices)])

[1 2]


TypeError: only size-1 arrays can be converted to Python scalars

In [1]:
import numpy as np

a = np.array([1,2,3,4,5])

In [2]:
print(a)

[1 2 3 4 5]


In [3]:
print(a.T)

[1 2 3 4 5]


In [7]:
print(np.tile(a, (4,2)))

[[1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]]


In [8]:
a.shape = (5,1)

In [9]:
a

array([[1],
       [2],
       [3],
       [4],
       [5]])