In [1]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

In [2]:
#define parameters
steps = 20
epochs = 25
batch_size = 8

In [ ]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 396 --epochs 25 \
--weights "../../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 1 \
--compute-val-loss\
csv "../OP_train_set_14-04.csv" "../classes.csv" \
--val-annotations "../OP_val_set_14-04.csv"

Using TensorFlow backend.
2020-04-30 07:26:57.834520: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-04-30 07:26:57.836101: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-04-30 07:26:58.764442: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-30 07:26:58.792444: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-30 07:26:58.793528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-128.    ,  -32.    ,  128.    ,   32.    ],
       [-161.2672,  -40.3168,  161.2672,   40.3168],
       [-203.1872,  -50.7968,  203.1872,   50.7968]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-256.    ,  -64.    ,  256.    ,   64.    ],
       [-322.5344,  -80.6336,  322.5344,   80.6336],
       [-406.3744, -101.5936,  406.3744,  101.5936]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-512.    , -128.    ,  512.    ,  128.    ],
       [-645.0688, -161.2672,  645.0688,  161.2672],
       [-812.7488, -203.1872,  812.7488,  203.1872]], dtype=float32)> anchors
Model: "retinanet"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer) 

Epoch 1/25
2020-04-30 07:27:24.975615: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-30 07:27:27.353918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
  8/396 [..............................] - ETA: 23:39 - loss: 4.4838 - bbox_regression_loss: 3.2908 - classification_loss: 1.1930../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_497.png with id 168 (shape (720, 1280, 3)) contains the following invalid boxes [[868.80414  190.12132  825.9837   171.78123  904.66656  -11.927582
  947.487      6.412506]] or angles [[-0.68998481 -0.72382385]].
  annotations['angles'][invalid_indices, :]
 33/396 [=>............................] - ETA: 14:28 - loss: 4.4112 - bbox_regression_loss: 3.2336 - classification_loss: 1.1776../../RetinaNet_Rot

106/396 [=======>......................] - ETA: 7:10 - loss: 1.5957 - bbox_regression_loss: 1.3647 - classification_loss: 0.2310../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_492.png with id 256 (shape (720, 1280, 3)) contains the following invalid boxes [[868.0336   188.71841  824.2425   169.69699  903.3951   -12.527908
  947.1862     6.493515]] or angles [[-0.68254528 -0.73084331]].
  annotations['angles'][invalid_indices, :]
173/396 [============>.................] - ETA: 5:46 - loss: 1.5084 - bbox_regression_loss: 1.2920 - classification_loss: 0.2164../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_496.png with id 100 (shape (720, 1280, 3)) contains the following invalid boxes [[867.3522    189.97424   825.7135    172.0376    904.89087   -11.766