In [1]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

In [2]:
#define parameters
steps = 20
epochs = 25
batch_size = 8

## Train on On Pallet

In [5]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 396 --epochs 25 \
--weights "../../RetinaNet_with_Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 1 \
--compute-val-loss\
--name "Rotated_Comb_OP_rectified_train_set_13-05_01" \
csv "../OP_rectified_train_set_13-05.csv" "../classes.csv" \
--val-annotations "../OP_rectified_val_set_13-05.csv"

Using TensorFlow backend.
2020-05-13 12:11:27.498178: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-13 12:11:27.499723: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-05-13 12:11:28.426469: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-13 12:11:28.454379: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 12:11:28.455398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-128.    ,  -32.    ,  128.    ,   32.    ],
       [-161.2672,  -40.3168,  161.2672,   40.3168],
       [-203.1872,  -50.7968,  203.1872,   50.7968]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-256.    ,  -64.    ,  256.    ,   64.    ],
       [-322.5344,  -80.6336,  322.5344,   80.6336],
       [-406.3744, -101.5936,  406.3744,  101.5936]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-512.    , -128.    ,  512.    ,  128.    ],
       [-645.0688, -161.2672,  645.0688,  161.2672],
       [-812.7488, -203.1872,  812.7488,  203.1872]], dtype=float32)> anchors
regression Tensor("split/stack:0", shape=(None, None, 4), dtype=float32)
other Tensor("split/stack_1:0", shape=(None, None, 2), dtype=float32)
boxes Tensor("clipped_boxes/stack:0", shape=(None, None, 4), dtype=float32)
Model: "retinanet"


Total params: 36,327,637
Trainable params: 36,221,397
Non-trainable params: 106,240
__________________________________________________________________________________________________
None
Epoch 1/25
2020-05-13 12:11:48.332070: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-13 12:11:49.339391: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
395/396 [============================>.] - ETA: 0s - loss: 3.3849 - bbox_regression_loss: 2.7041 - classification_loss: 0.6808../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_490.png with id 88 (shape (720, 1280, 3)) contains the following invalid boxes [[868.3233   187.75914  824.27985  168.72427  902.04706  -11.215927
  946.0905     7.818939]] or angles [[-0.68522838 -0.72832827]].
  annota

../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_496.png with id 94 (shape (720, 1280, 3)) contains the following invalid boxes [[867.3522    189.97424   825.7135    172.0376    904.89087   -11.766983
  946.52954     6.1696625]] or angles [[-0.68696358 -0.72669184]].
  annotations['angles'][invalid_indices, :]
../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_497.png with id 95 (shape (720, 1280, 3)) contains the following invalid boxes [[868.80414  190.12132  825.9837   171.78123  904.66656  -11.927582
  947.487      6.412506]] or angles [[-0.68998481 -0.72382385]].
  annotations['angles'][invalid_indices, :]
../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Data

Epoch 13/25
396/396 [==============================] - 131s 331ms/step - loss: 0.2772 - bbox_regression_loss: 0.2573 - classification_loss: 0.0200 - val_loss: 0.8323 - val_bbox_regression_loss: 0.5341 - val_classification_loss: 0.1491
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1025 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00013: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_13.h5
Epoch 14/25
396/396 [==============================] - 131s 330ms/step - loss: 0.2592 - bbox_regression_loss: 0.2417 - classification_loss: 0.0175 - val_loss: 0.8440 - val_bbox_regression_loss: 0.5533 - val_classification_loss: 0.1500
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1025 instances of class Brick with average precision

## Continue Training from Snapshot

In [ ]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 99 --epochs 50 \
--snapshot "./02 On Pallet Dataset/01 Snapshots/resnet50_csv_25.h5" \
--initial-epoch 25 \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 4 \
--compute-val-loss\
--random-transform\
--name "Rotated_Comb_OP_train_set_14-04_rndTrans_BS4_25-50" \
csv "../OP_train_set_14-04.csv" "../classes.csv" \
--val-annotations "../OP_val_set_14-04.csv"

## Train on Simple Dataset

In [1]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 162 --epochs 25 \
--weights "../../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--snapshot-path "./01 Simple Dataset/01 Snapshots" \
--batch-size 1 \
--compute-val-loss\
--name "Rotated_Comb_train_set_18-03_05" \
csv "../train_set_18-03.csv" "../classes.csv" \
--val-annotations "../val_set_18-03.csv"

Using TensorFlow backend.
2020-05-05 01:35:29.749810: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-05 01:35:29.806443: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-05-05 01:35:32.405989: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-05 01:35:32.481301: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-05 01:35:32.482430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-128.    ,  -32.    ,  128.    ,   32.    ],
       [-161.2672,  -40.3168,  161.2672,   40.3168],
       [-203.1872,  -50.7968,  203.1872,   50.7968]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-256.    ,  -64.    ,  256.    ,   64.    ],
       [-322.5344,  -80.6336,  322.5344,   80.6336],
       [-406.3744, -101.5936,  406.3744,  101.5936]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-512.    , -128.    ,  512.    ,  128.    ],
       [-645.0688, -161.2672,  645.0688,  161.2672],
       [-812.7488, -203.1872,  812.7488,  203.1872]], dtype=float32)> anchors
regression Tensor("split/stack:0", shape=(None, None, 4), dtype=float32)
other Tensor("split/stack_1:0", shape=(None, None, 2), dtype=float32)
boxes Tensor("clipped_boxes/stack:0", shape=(None, None, 4), dtype=float32)
Model: "retinanet"


Epoch 1/25
2020-05-05 01:35:57.864225: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-05 01:36:00.434490: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
162/162 [==============================] - 63s 390ms/step - loss: 3.1729 - bbox_regression_loss: 2.3892 - classification_loss: 0.7838 - val_loss: 2.7372 - val_bbox_regression_loss: 1.6873 - val_classification_loss: 0.2012
Running network: 100% (40 of 40) |#######| Elapsed Time: 0:00:06 Time:  0:00:06
Parsing annotations: 100% (40 of 40) |###| Elapsed Time: 0:00:00 Time:  0:00:00
640 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00001: saving model to ./01 Simple Dataset/01 Snapshots/resnet50_csv_01.h5
Epoch 2/25
162/162 [==============================] - 48s 295ms/step - loss: 1.5231 - bbox_regression_loss: 1.3667 - classification_loss: 0.1563 - val_loss: 2.0113 - v