In [1]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

In [2]:
#define parameters
steps = 20
epochs = 25
batch_size = 8

In [1]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 396 --epochs 25 \
--weights "../../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 1 \
--compute-val-loss\
csv "../OP_train_set_14-04.csv" "../classes.csv" \
--val-annotations "../OP_val_set_14-04.csv"

Using TensorFlow backend.
2020-04-30 08:44:52.477518: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-04-30 08:44:52.479034: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-04-30 08:44:53.395013: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-30 08:44:53.421533: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-30 08:44:53.422543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-128.    ,  -32.    ,  128.    ,   32.    ],
       [-161.2672,  -40.3168,  161.2672,   40.3168],
       [-203.1872,  -50.7968,  203.1872,   50.7968]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-256.    ,  -64.    ,  256.    ,   64.    ],
       [-322.5344,  -80.6336,  322.5344,   80.6336],
       [-406.3744, -101.5936,  406.3744,  101.5936]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-512.    , -128.    ,  512.    ,  128.    ],
       [-645.0688, -161.2672,  645.0688,  161.2672],
       [-812.7488, -203.1872,  812.7488,  203.1872]], dtype=float32)> anchors
Model: "retinanet"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer) 

Epoch 1/25
2020-04-30 08:45:13.514502: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-30 08:45:14.483814: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
 74/396 [====>.........................] - ETA: 2:32 - loss: 4.2136 - bbox_regression_loss: 3.1294 - classification_loss: 1.0842../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_491.png with id 28 (shape (720, 1280, 3)) contains the following invalid boxes [[867.08344  187.72015  824.8344   168.87415  905.7642   -12.554611
  948.01324    6.291397]] or angles [[-0.66808735 -0.74408285]].
  annotations['angles'][invalid_indices, :]
 81/396 [=====>........................] - ETA: 2:24 - loss: 4.1700 - bbox_regression_loss: 3.1185 - classification_loss: 1.0516../../RetinaNet_Rotate

151/396 [==========>...................] - ETA: 1:14 - loss: 1.7936 - bbox_regression_loss: 1.5669 - classification_loss: 0.2267../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_491.png with id 28 (shape (720, 1280, 3)) contains the following invalid boxes [[867.08344  187.72015  824.8344   168.87415  905.7642   -12.554611
  948.01324    6.291397]] or angles [[-0.66808735 -0.74408285]].
  annotations['angles'][invalid_indices, :]
180/396 [============>.................] - ETA: 1:05 - loss: 1.7497 - bbox_regression_loss: 1.5273 - classification_loss: 0.2223../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_497.png with id 168 (shape (720, 1280, 3)) contains the following invalid boxes [[868.80414  190.12132  825.9837   171.78123  904.66656  -11.927582
  

Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00009: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_09.h5
Epoch 10/25
396/396 [==============================] - 132s 333ms/step - loss: 0.3111 - bbox_regression_loss: 0.2816 - classification_loss: 0.0295 - val_loss: 0.0143 - val_bbox_regression_loss: 0.4252 - val_classification_loss: 0.0432
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00010: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_10.h5
Epoch 11/25
396/396 [==============================] - 132s 333ms/step - loss: 0.2979 - bbox_regression_loss: 0.2705 - classifica

396/396 [==============================] - 133s 336ms/step - loss: 0.1725 - bbox_regression_loss: 0.1639 - classification_loss: 0.0086 - val_loss: 1.6960e-05 - val_bbox_regression_loss: 0.3000 - val_classification_loss: 0.0254
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:15 Time:  0:00:15
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00024: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_24.h5
Epoch 25/25
396/396 [==============================] - 133s 336ms/step - loss: 0.1649 - bbox_regression_loss: 0.1567 - classification_loss: 0.0082 - val_loss: 8.4110e-06 - val_bbox_regression_loss: 0.2816 - val_classification_loss: 0.0255
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:15 Time:  0:00:15
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.