In [1]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt

In [2]:
#define parameters
steps = 20
epochs = 25
batch_size = 8

In [1]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 99 --epochs 25 \
--weights "../../RetinaNet with Angle/keras_retinanet/resnet50_coco_best_v2.1.0.h5" \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 4 \
--compute-val-loss\
--random-transform\
--name "Rotated_Comb_OP_train_set_14-04_rndTrans_BS4" \
csv "../OP_train_set_14-04.csv" "../classes.csv" \
--val-annotations "../OP_val_set_14-04.csv"

Using TensorFlow backend.
2020-05-04 03:20:17.892103: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-04 03:20:17.893570: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Creating model, this may take a second...
2020-05-04 03:20:18.805048: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-04 03:20:18.833553: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-04 03:20:18.834614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00Gi

tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-128.    ,  -32.    ,  128.    ,   32.    ],
       [-161.2672,  -40.3168,  161.2672,   40.3168],
       [-203.1872,  -50.7968,  203.1872,   50.7968]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-256.    ,  -64.    ,  256.    ,   64.    ],
       [-322.5344,  -80.6336,  322.5344,   80.6336],
       [-406.3744, -101.5936,  406.3744,  101.5936]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-512.    , -128.    ,  512.    ,  128.    ],
       [-645.0688, -161.2672,  645.0688,  161.2672],
       [-812.7488, -203.1872,  812.7488,  203.1872]], dtype=float32)> anchors
regression Tensor("split/stack:0", shape=(None, None, 4), dtype=float32)
other Tensor("split/stack_1:0", shape=(None, None, 2), dtype=float32)
boxes Tensor("clipped_boxes/stack:0", shape=(None, None, 4), dtype=float32)
Model: "retinanet"


Epoch 1/25
../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_490.png with id 21 (shape (720, 1280, 3)) contains the following invalid boxes [[868.3233   187.75914  824.27985  168.72427  902.04706  -11.215927
  946.0905     7.818939]] or angles [[-0.68522838 -0.72832827]].
  annotations['angles'][invalid_indices, :]
../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_493.png with id 31 (shape (720, 1280, 3)) contains the following invalid boxes [[869.54724   189.71188   824.7621    170.633     902.9514    -12.906097
  947.7366      6.1727905]] or angles [[-0.69278667 -0.72114259]].
  annotations['angles'][invalid_indices, :]
../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../0

48/99 [=============>................] - ETA: 50s - loss: 3.2196 - bbox_regression_loss: 2.8730 - classification_loss: 0.3466../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_498.png with id 226 (shape (720, 1280, 3)) contains the following invalid boxes [[869.666     188.94604   824.5969    169.95627   901.71765   -13.077179
  946.78674     5.9125977]] or angles [[-0.6984645  -0.71564471]].
  annotations['angles'][invalid_indices, :]
59/99 [================>.............] - ETA: 39s - loss: 3.1346 - bbox_regression_loss: 2.7967 - classification_loss: 0.3379../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_496.png with id 100 (shape (720, 1280, 3)) contains the following invalid boxes [[867.3522    189.97424   825.7135    172.0376    904.89087   -11.76

Epoch 10/25
99/99 [==============================] - 107s 1s/step - loss: 0.6945 - bbox_regression_loss: 0.6045 - classification_loss: 0.0900 - val_loss: 0.7583 - val_bbox_regression_loss: 0.5371 - val_classification_loss: 0.0772
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00010: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_10.h5
Epoch 11/25
99/99 [==============================] - 107s 1s/step - loss: 0.6465 - bbox_regression_loss: 0.5671 - classification_loss: 0.0794 - val_loss: 0.7004 - val_bbox_regression_loss: 0.5021 - val_classification_loss: 0.0741
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
m

Epoch 25/25
99/99 [==============================] - 107s 1s/step - loss: 0.4161 - bbox_regression_loss: 0.3729 - classification_loss: 0.0432 - val_loss: 0.4885 - val_bbox_regression_loss: 0.3520 - val_classification_loss: 0.0410
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:14 Time:  0:00:14
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00025: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_25.h5
{'val_loss': [3.793961524963379, 2.502951145172119, 2.024339437484741, 1.5875506401062012, 1.2608405351638794, 1.1204584836959839, 0.9547200798988342, 0.8556777238845825, 0.8646806478500366, 0.7582628726959229, 0.7003591060638428, 0.6852849721908569, 0.6645893454551697, 0.6598690748214722, 0.6720027327537537, 0.5968151688575745, 0.5402076840400696, 0.5409390330314636, 0.5396220684051514, 0.5251045823097229, 0.5130172967910767, 0.5727106332778931, 0

## Continue Training from Snapshot

In [2]:
!python "../../RetinaNet_Rotated_Comb/keras_retinanet/bin/train.py" --steps 99 --epochs 50 \
--snapshot "./02 On Pallet Dataset/01 Snapshots/resnet50_csv_25.h5" \
--initial-epoch 25 \
--snapshot-path "./02 On Pallet Dataset/01 Snapshots" \
--batch-size 4 \
--compute-val-loss\
--random-transform\
--name "Rotated_Comb_OP_train_set_14-04_rndTrans_BS4_25-50" \
csv "../OP_train_set_14-04.csv" "../classes.csv" \
--val-annotations "../OP_val_set_14-04.csv"

Using TensorFlow backend.
2020-05-04 04:22:02.312505: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-04 04:22:02.314112: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Loading model, this may take a second...
2020-05-04 04:22:03.269229: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-04 04:22:03.294313: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-04 04:22:03.295312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:05.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00GiB

boxes Tensor("clipped_boxes/stack:0", shape=(None, None, 4), dtype=float32)
Model: "retinanet"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, None, None, 3 0                                            
__________________________________________________________________________________________________
padding_conv1 (ZeroPadding2D)   (None, None, None, 3 0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, None, None, 6 9408        padding_conv1[0][0]              
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, None, None, 6 256         conv1[0][0]                      
______________

Epoch 26/50
../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_490.png with id 21 (shape (720, 1280, 3)) contains the following invalid boxes [[868.3233   187.75914  824.27985  168.72427  902.04706  -11.215927
  946.0905     7.818939]] or angles [[-0.68522838 -0.72832827]].
  annotations['angles'][invalid_indices, :]
../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_493.png with id 31 (shape (720, 1280, 3)) contains the following invalid boxes [[869.54724   189.71188   824.7621    170.633     902.9514    -12.906097
  947.7366      6.1727905]] or angles [[-0.69278667 -0.72114259]].
  annotations['angles'][invalid_indices, :]
2020-05-04 04:22:26.250588: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library lib

11/99 [==>...........................] - ETA: 1:27 - loss: 0.4145 - bbox_regression_loss: 0.3751 - classification_loss: 0.0395../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_498.png with id 226 (shape (720, 1280, 3)) contains the following invalid boxes [[869.666     188.94604   824.5969    169.95627   901.71765   -13.077179
  946.78674     5.9125977]] or angles [[-0.6984645  -0.71564471]].
  annotations['angles'][invalid_indices, :]
12/99 [==>...........................] - ETA: 1:26 - loss: 0.4189 - bbox_regression_loss: 0.3783 - classification_loss: 0.0406../../RetinaNet_Rotated_Comb/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:197: UserWarning: Image ../../../03 Data/Dataset2_onPallet/OP_colorIMG_500.png with id 66 (shape (720, 1280, 3)) contains the following invalid boxes [[867.7198    186.29915   821.91      167.41571   898.0103    -17.1

Epoch 34/50
99/99 [==============================] - 108s 1s/step - loss: 0.3435 - bbox_regression_loss: 0.3065 - classification_loss: 0.0370 - val_loss: 0.4893 - val_bbox_regression_loss: 0.3613 - val_classification_loss: 0.0360
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:15 Time:  0:00:15
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00034: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_34.h5
Epoch 35/50
99/99 [==============================] - 108s 1s/step - loss: 0.3464 - bbox_regression_loss: 0.3097 - classification_loss: 0.0367 - val_loss: 0.4632 - val_bbox_regression_loss: 0.3291 - val_classification_loss: 0.0345
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:15 Time:  0:00:15
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
m

Epoch 49/50
99/99 [==============================] - 108s 1s/step - loss: 0.2761 - bbox_regression_loss: 0.2492 - classification_loss: 0.0270 - val_loss: 0.3518 - val_bbox_regression_loss: 0.2794 - val_classification_loss: 0.0281
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:15 Time:  0:00:15
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
mAP: 0.0000

Epoch 00049: saving model to ./02 On Pallet Dataset/01 Snapshots/resnet50_csv_49.h5
Epoch 50/50
99/99 [==============================] - 108s 1s/step - loss: 0.2814 - bbox_regression_loss: 0.2550 - classification_loss: 0.0264 - val_loss: 0.3611 - val_bbox_regression_loss: 0.2807 - val_classification_loss: 0.0269
Running network: 100% (99 of 99) |#######| Elapsed Time: 0:00:15 Time:  0:00:15
Parsing annotations: 100% (99 of 99) |###| Elapsed Time: 0:00:00 Time:  0:00:00
1157 instances of class Brick with average precision: 0.0000
m